### PR TITLE
[Awaiting Feedback] Roslyn-based Code Generation

### PR DESCRIPTION
**Pull request by kentcb**
## What is this?

This PR adds several new projects to the core solution to support a Roslyn-based code generator:

* *BrightstarDB.CodeGeneration* : this is the core code generation logic - the brains of the operation
* *BrightstarDB.CodeGeneration.Tests* : contains tests for the core code generation logic
* *BrightstarDB.CodeGeneration.Console* : a console-based code generator
* *BrightstarDB.CodeGeneration.T4* : a T4 template based code generator

## What's cool about it?

* it generates both C# and VB code
* it allows you to use `nameof` in your attributes: `[InverseProperty(nameof(IParentEntity.Children))]`. No more magic strings!
* it supports multiple tools for generating the code - console or T4 - which means it is usable outside of VS
* on top of that, the T4 template is almost completely agnostic of VS. I will test this once I have NuGets, but it should be possible to use from Xamarin Studio with a couple of tweaks

## Task List

- [x] Create the requisite project structure in the core solution
- [X] Write the core code generation logic
- [X] Write tests for the code generation logic when generating C#
- [x] Write tests for the code generation logic when generating VB
- [X] Write a console-based code generator
- [X] Test the console-based generator
- [X] Write a T4-based code generator
- [x] Test the T4-based code generator
- [x] Create NuGet packages for both the console and T4 based generators
- [x] Test the NuGets

### Console

You'd install the *BrightstarDB.CodeGeneration.Console* NuGet package. This is a solution-level package that will add a tool to your packages structure. It is invoked like this:

```
BrightstarDB.CodeGeneration.Console path/to/MySolution.sln My.Context.Namespace Output.cs
```

One can optionally specify the context name (defaults to "EntityContext") or force the language (defaults to whatever makes sense for the output file's extension).

### T4

You'd install the *BrightstarDB.CodeGeneration.T4* NuGet package. This adds a file called *EntityContext.tt* to your project. You can move this file around as you see fit and it affects the namespace of the context only (not the entities).

The execution of this template is actually resolving the code generation assembly in the tools folder of the package and forwarding the request on. All the T4 template really does is spit out the result of calling the core logic.

## Questions for you

* the existing template logic seems to support `ISet<T>` in one place, but then only `ICollection<T>` in another. My implementation therefore only supports `ICollection<T>`. Is this correct?
* the existing template logic somehow strips certain attributes from propagating through to the generated properties, but I couldn't figure out exactly how/what it was stripping. My implementation strips any attribute in the `BrightstarDB.EntityFramework` namespace. All other attributes are propagated. Is this OK?

### CODE REVIEW

**Comment by kentcb** [comment]
Not sure why all your commits got included in this PR. I may have done something wrong. Let me know if you need me to recreate the PR.

**Comment by kal** [comment]
Hi Kent,

Not sure what happened to my last comment !

This all looks great - I have it compiling here with a couple of minor project file tweaks. The one thing I would like to do is to get the main EF tests running of the new T4 template rather than the old one, maybe using a "simulated" NuGet package that can be created by the project as a before build step. That way we can make use of all of the previously written tests (though for the most part they really test EF rather than the code generation, but its good to do from a regression point of view).

I think that would be easier to do with this PR merged into develop. So I'm going to do that now and we may need to collaborate a bit on getting all the bits in the right place.

This is great work! Thanks for sharing it.

Cheers

Kal

**Comment by kentcb** [comment]
np Kal. Note that the codegen projects now produce NuGet packages (they're spat into the output directory under a NuGet subdirectory). The build script for producing them differs from what was there already because they're not simple project NuGets - they're tools/content NuGets instead.

Anyways, ping me if you need anything.

**Comment by kal** [comment]
I'm getting an error trying to run the codegen from inside VS2013. It looks like it might be necessary to bundle a recompiled version of Roslyn that uses MSBuild 4.0 otherwise we end up with a hard dependency on VS2015

**Comment by kentcb** [comment]
@kal It runs fine for me from within 2013. What error are you getting?

**Comment by kal** [comment]
I'm getting a file not found exception from the assembly loader, looking
for Microsoft.Build 14.0.0.0. This assembly is part of the VS2015 toolkit
and all the info I have found about this indicates that you need to have
CTP5 or later installed. I'm guessing that your machine probably already
has VS2015 installed and so the assembly is found.

I think this probably means that the way to go is to keep the old TT file
for now, and make it clear to folks that they can alternatively use the
codegen command line or the codegen-based TT file, but that it requires
VS2015 to be installed. In a few months, this won't be a big issue for
anyone and maybe once 2015 is out we can deprecate the old TT file and swap
things around so that codegen becomes the default for EF.

**Comment by kentcb** [comment]
Ah, I see. Yes, I have 2015 and 2013 side by side. I do wonder whether this is a temporary pre-release issue only. That is, whether Roslyn will eventually depend on an appropriate NuGet package rather than what's available on the local machine.

**Pull request merged**
