### PR TITLE
Adds initial work on .net standard refresh of B*

### PR DESCRIPTION
**Pull request by dgerding**
-new standard folder in src has two projects, BrightstarDBStandard and BrightstarDB.tests

-BrightstarDBStandard is .net 2.0 project with standalone (no linked files) brightstardb project with updated nugets etc..  This is a very quick "port" of the portable project but still needs remaining compiler directives reviewed/cleaned out.  Adds Dynamic since .net standard wasn't complaining about it.

-BrightstarDB.Tests is net core base nunit project with small portion of working tests copied in from old BrightstarDB.tests.

### CODE REVIEW

**Comment by kal** [comment]
Hi @dgerding !

Thanks for the PR. I've grabbed it and got it building locally. However I have a few questions/comments.
I think that we can drop the copied Mono crypto code and use the standard library. I hope that we can also drop the remotion.linq code and use their NuGet package (less sure about that). 

In fact, in general I think that a lot of the restrictions I had to work around on the portable platforms probably don't apply for a .NET Standard 2.0 target and I wonder if actually we would be better off taking a different approach. I'm quite happy to be brutal about dropping support for older platforms so I actually wonder if it wouldn't be better to change the main B* solution to contain multi-targetting projects that target .NET 4.5 and .NET Standard 2.0. I think with those two we would essentially cover all of the same platforms (via NET Standard 2) as well as not leave behind those who are stuck on .NET Framework 4.5/4.6. I'm thinking that by doing this we (a) save a lot of painful backporting of fixes and/or managing linked sources and (b) massively streamline the source. As far as I can see the only downside is that if someone is trying to use B* as a library in an old-style portable project they might be a bit stuck - but I don't know of anyone doing that, and they could always take a fork from our codebase if they really need it.

What do you think?

**Comment by dgerding** [comment]
Hi @kal,
I agree about removing the old "prosthetic" code that you used to get portable build working.  Also agree no linked sources.  The other thing that got me excited was all the talk of .net core performance being a lot higher, especially in string intensive domains.  (I'll see if I can verify that mythology :) .)

But I confess my understanding was that by targeting .net standard one could use the resulting dlls in both .net core contexts _and_ .net 45/46 contexts.  I think we get multiple target dlls, but there's still just one .net standard project, right?  

I'd be happy to continue poking along the lines of doing the grunt work of just incrementally getting the tests to work while also incrementally removing the cruft code.   Refactoring the core db project to be contemporary in terms of dependencies and build targets seems like a good first step.  If you'd help by answering questions I could probably make progress on that effort and then we could turn to the same work with the codegen bit.

Oh, also agree with a "plain vanilla" asp.net core server transition as a goal.

I suspect the other bottleneck we might hit soon is in the codgen dependencies vis a vis .net core support.

Not sure if we are saying different things or the same thing! ?   

:)
 Dave

**Comment by dgerding** [comment]
Here's the link about string performance.  I guess I'm assuming that all that rdf leans into string evaluation more than average code.

https://dotnetcoretutorials.com/2018/08/22/are-string-equals-and-string-indexof-that-much-faster-in-net-core-2-1/

**Comment by kal** [comment]
Hi @dgerding ,

> But I confess my understanding was that by targeting .net standard one could use the resulting dlls in both .net core contexts _and_ .net 45/46 contexts. I think we get multiple target dlls, but there's still just one .net standard project, right?

That's how I understand it. It works OK for dotNetRDF - and we still produce a .NET 4.0 assembly as well as .NET Standard assemblies from the same project.

> I'd be happy to continue poking along the lines of doing the grunt work of just incrementally getting the tests to work while also incrementally removing the cruft code. Refactoring the core db project to be contemporary in terms of dependencies and build targets seems like a good first step. If you'd help by answering questions I could probably make progress on that effort and then we could turn to the same work with the codegen bit.

That sounds like a great plan. I tried a quick and dirty hack of the "core" solution to see if I could get something building quickly, but hit issues with changes in the API of Remotion.Linq which is needed for the LINQ-to-SPARQL query provider. Unfortunately just dropping back to an older version isn't a viable workaround as the versions with the old API don't support .NET Standard 1.x and only support .NET Standard 2 by using the .NET Framework 4.6.1 assembly in the NuGet package. So the "proper" solution here would be to update the version of Remotion.Linq we are using and fix all the code that is broken by the changes in API.

 
> Oh, also agree with a "plain vanilla" asp.net core server transition as a goal.
> 
> I suspect the other bottleneck we might hit soon is in the codgen dependencies vis a vis .net core support.

I didn't manage to get as far as hacking these projects, but hopefully a vanilla asp.net core server would be straightforward enough. I agree with you that the codegen is likely to be painful to migrate.

> Not sure if we are saying different things or the same thing! ?

Looks like we are on the same page! Question is what is the best way to proceed on this and share some of the work out. The problem is going to be that there are going to be a lot of fixes that are needed before we can even get started on the tests. If you want to have a go at that then I would definitely encourage you to do so. I'll try and provide support / answer questions. I may have a bit of time over the weekend to work a bit more on my local changes though and if I can get something at least building then that might be better to give you a bit of a head start. What do you think? Are you happy to hold off for a few days while I see if I can make a bit of progress?

Cheers

Kal

**Comment by dgerding** [comment]
HI @kal,
The code I shared was how far I got after first trying to "just convert" the portable project to a .net standard target and then, if I remember right, the net core version.  The version I shared is a little bit of both and just enough effort to get it to compile and then pass those initial tests.

You might find working against the project I've pushed easier since I also tried to "simply upgrade" the existing projects with no luck.  Of course, I'm coming at it from a "very little solution knowledge, how can I just get this to work with contemporary Xamarin, Unity, .net core?", perspective.  As the architect I'm sure you've got other priorities :)

Let me know when you want me to do more.  I can also push ahead on my franken-hack approach if you think there's utility there.  

Holding off. 

Dave

**Comment by kal** [comment]
Hi @dgerding - I'm going to close this PR as I think that the changes I've pushed to develop should have everything you need to build a modern Xamarin/Unity/.NET Core application. If not please open a new issue!

**Comment by dgerding** [comment]
Hi @Kal,
Pulling newest to look at all the good changes now.  Hope the pull request was at least inspiring :)  Looking forward to try things out.

Thanks!
Dave G

**Pull request closed without merging**
